- girder/molecules/server/calculation.py
The index is already a zero-based index, no need to decrement again.
Apply the slice to other parameters too in order to only return data
for the selected mode.
> The modes returned were off by one, fixed

- girder/molecules/server/query.py
In the future we should store a lowercase version of these fields
so we can do direct matches ( using the index ... )
> Make queries case insensitive

- girder/molecules/server/avogadro.py
This is somewhat arbitrary, and we should likely expose this to the
RESTful API in the future to offer fine versus coarse cubes.
> Do some scaling of the spacing based on molecule size

- girder/molecules/server/calculation.py
- girder/molecules/server/models/cubecache.py
The cube cache is public API, and shouldn't need/require a user.
> Don't need current user for cache, public API

- girder/molecules/server/calculation.py
This ensures that proxied files (i.e. NEWT assetstore files) are downloaded
> Use file_model open syntax

- girder/molecules/server/models/molecule.py
Some of these attributes are not required for molecules. For instance,
if a molecule is created via xyz, a name will not necessarily be
given to it.
If there are any molecules in the database without a name, GET
'/molecules' would cause a server error.
This fixes the server error.
> Fix molecule server error if attributes missing

- girder/molecules/plugin_tests/molecules_test.py
This endpoint is used in openchemistrypy, so I wrote a brief test
for it.
> Added a test for GET "/molecules/inchikey"

- girder/molecules/server/molecule.py
For GET /molecules/inchikey/{inchikey}, the web api should have
an "inchikey" param, not "inchi".
This fixes it and makes it work properly.
> Fix web api param from "inchi" to "inchikey"

- girder/molecules/server/molecule.py
This prevents a server error when it tries to load the input data
as a json string but the input data may not be a json string.
> Molecule create: only check experiment for nwchem

- docker/Dockerfile
This option has been removed in pip 19.0. Its not clear why we were using it.
> Remove --process-dependency-links

- girder/molecules/server/experiment.py
- girder/molecules/server/nist.py
- requirements.txt
This PR intends to close https://github.com/OpenChemistry/42/issues/7. It contains the following changes:
1. A new `nist` module was added. It contains functions to download `jdx` files from NIST. It adds two dependecies: `bs4`, and `jcamp`.
1.  A `find_experiment()` function was modified to operate with the new added `nist` module. It returns a dictionary with spectrum's data. 
TODO:
> MongoChemServer changes to query spectra 

- girder/molecules/server/experiment.py
- girder/molecules/server/nist.py
- requirements.txt
This PR intends to close https://github.com/OpenChemistry/42/issues/7. It contains the following changes:
1. A new `nist` module was added. It contains functions to download `jdx` files from NIST. It adds two dependecies: `bs4`, and `jcamp`.
1.  A `find_experiment()` function was modified to operate with the new added `nist` module. It returns a dictionary with spectrum's data. 
TODO:
> MongoChemServer changes to query spectra

- girder/molecules/server/utilities/molecules.py
'chemical json' was used for cjson version 0. Allow
this key to be used.
> Allow 'chemical json' for cjson version key

- girder/molecules/server/molecule.py
They appear to have changed their API, not sure what the return is from
/sdf now, but file?format=sdf returns the SDF format we want.
> Updated to adapt to changed CACTUS API

- girder/molecules/server/chemspider.py
- girder/molecules/server/models/molecule.py
- girder/molecules/server/semantic/cheminf.py
- girder/molecules/server/utilities/molecules.py
This is done so that it is more easily detectable whether
a name has been set or not.
This is done as per the discussion [here](https://github.com/OpenChemistry/mongochemclient/pull/111).
> Do not add default names for molecules

- docker/Dockerfile
- girder/notebooks/notebooks/__init__.py
Here are the summaries of the commits:
Put girder config file in /etc/girder.cfg
============================
The previous location of the girder config file is no longer
supported as of [this commit](https://github.com/girder/girder/commit/fbe7a05895d99fe2de297a84a1e9341da1e48ccd).
Move the config file in /etc/girder.cfg instead.
Do not create a notebook if there is no assetstore
=====================================
As of girder 3, in mongochemdeploy, when ansible creates the first user
`mongochemdev`, it also tries to create a notebook due to the notebook
plugin, and an exception gets raised because there is no assestore yet.
Before girder 3, this wouldn't happen because the notebook plugin would
be explicitly enabled after the `mongochemdev` user was created. But in
girder 3, the …
> Updates for the girder 3 changes in past month

- girder/molecules/molecules/models/molecule.py
- girder/molecules/molecules/molecule.py
- girder/molecules/plugin_tests/molecules_test.py
Move formula search from `GET /molecules/search` to
`GET /molecules` for consistent searching.
As far as I can tell, `GET /molecules/search` for a formula was not being used anywhere. So this will hopefully not break anything.
> Move formula search to `GET /molecules`

- girder/molecules/molecules/calculation.py
- girder/molecules/molecules/models/molecule.py
- girder/molecules/molecules/molecule.py
- girder/molecules/molecules/utilities/pagination.py
Before, the number of matches was limited by the limit.
Now it is not, which can be helpful for pagination.
The reason Collection.count_documents() was used instead
of Cursor.count() is because Cursor.count() is deprecated
in favor of Collection.count_documents().
> Count total number of matches (no limit) for GET

- girder/molecules/molecules/models/molecule.py
Using fields like this is a simpler and more efficient
way to choose the keys we want to get from molecules.
For fields like `name` where it may or may not be present,
it does not return anything if `name` is not present.
> Use fields to get specific keys from molecules

- girder/molecules/molecules/molecule.py
This something I've been meaning to add for a while.
It must be present in order for the "id" to show up
in the interactive web API.
> Add molecule id to GET /molecules/{id}

- girder/molecules/molecules/models/molecule.py
- girder/molecules/molecules/molecule.py
In the minValues parameter, one can pass in things like:
```
{ "properties.heavyAtomCount": 4 }
```
and the results will only contain molecules that have at
least 4 heavy atoms. The maxValues parameter can be used
in a similar way.
If both the minValues and maxValues parameters are used, then
the results will satisfy both.
> Allow molecules to be searched with min/max values

- girder/molecules/molecules/models/molecule.py
- girder/molecules/molecules/molecule.py
The molecules query is being added to GET /molecules so that we can use 
it in oc-web-components without having to add logic that determines
whether to use GET /molecules or GET /molecules/search.
If the molecules query ("queryString") parameter is present, then all 
other search parameters will be ignored.
> Allow use of molecules query in GET /molecules

- flask/openbabel/src/openbabel_api.py
- girder/molecules/plugin_tests/molecules_test.py
Converting to xyz has potentially been causing some issues with the
inchi generation. Perhaps it is because the molecule loses the
connectivity and needs to perceive it again - and all atoms get
placed at (0, 0, 0), so bond perception may not be working.
For instance, if we create an inchi from ethane, CC, but we convert
to xyz first, it places both carbon atoms at (0, 0, 0), and only
four hydrogen atoms are added around the two carbon atoms that are
sitting on top of each other. It produces this inchi and inchikey:
```
InChI=1S/2CH4/h2*1H4
CREMABGTGYGIQB-UHFFFAOYSA-N
```
Instead of what appears to be the correct inchi and inchikey:
```
InChI=1S/C2H6/c1-2/h1-2H3
OTMSDBZUPAUEDD-UHFFFAOYSA-N
```
Skipping the xyz conversion seems to fix the issue, and we get the
correct inchi.
However, we …
> When generating inchi, do not convert to xyz first

- girder/molecules/molecules/models/molecule.py
- girder/molecules/molecules/molecule.py
These are not actually used anywhere, and we decided to start
using the mongochem query features to do this kind of thing. Thus,
they are not necessary.
> Remove molecules GET min/max values from interface

- girder/molecules/molecules/utilities/molecules.py
Compared to SMILES, InChI can perhaps be less ambiguous for defining
molecular structure. We shoud thus use it for generating properties
and other things rather than SMILES.
Thus, we now attempt to convert to InChI at the beginning, and use
it to generate other properties.
> Use inchi instead of smiles to generate properties

- docker/girder/Dockerfile
We need this for deployments that share a cluster.
> Add autojoin plugin

- girder/app/app/user.py
- girder/molecules/molecules/calculation.py
- girder/molecules/molecules/molecule.py
This allows api keys that have custom access permissions to
interface with the endpoints.
Fixes: #157
> Add token scopes to @access.user decorators

- girder/molecules/molecules/utilities/molecules.py
This modifies some of the logic blocks to improve readability.
It also skips a conversion from cjson to cjson in Avogadro2, and
just keeps the cjson that was passed in.
> Improve the readability of create_molecule()

- girder/molecules/molecules/calculation.py
- girder/molecules/molecules/models/calculation.py
This puts the input parameter hashing on the server instead of
on the client side for searching for a calculation. It prevents
clients from having to ensure they hash the input parameters in
the same way that the server does it.
It is intended to send this via url quoted data. However, it
seems to work fine without url quoting also... (probably as long
as there are no percent signs in the string).
> Hash input params on server for calc search

- girder/molecules/molecules/calculation.py
- girder/molecules/molecules/utilities/async_requests.py
If the ansynchronous orbital calculation returns a status other than 200, update
the client notification and raise an exception on the next call to the endpoint.
Signed-off-by: Brianna Major <brianna.major@kitware.com>
> Check for exception on asynchronous orbital calculation

- girder/molecules/molecules/calculation.py
Otherwise, we get an error if we try to use a token without full
access.
> Add token scope to needed endpoint

- docker/flask/openbabel/Dockerfile
- flask/openbabel/README.md
- flask/openbabel/requirements.txt
- flask/openbabel/src/openbabel_api.py
Since Ubuntu's `libopenbabel-dev` and the openbabel Linux wheels on
PyPI are not up-to-date, we moved to installing openbabel via conda
in the conda-forge channel.
The only migration change I could find is that we need to import pybel
via `from openbabel import pybel` instead of just `import pybel`.
Using the new image, I ran the pytests, and tried out all of the
notebooks, and I did not notice anything unusual. But it might be good
for someone else to double-check.
The handling of implicit hydrogens has changed a little bit, which may
affect us somewhere, but I did not immediately see any differences in
our examples.
Migration instructions can be found [here](https://open-babel.readthedocs.io/en/latest/UseTheLibrary/migration.html).
> Upgrade openbabel to 3.0.0

- girder/molecules/molecules/calculation.py
When an optimization calculation is performed, and a new geometry is
generated as a result, save the optimized geometry ID in the calculation
as "optimizedGeometryId".
"geometryId" is not used here because, if a specific geometry was chosen
as input for the calculation, "geometryId" is the ID of that input
geometry.
The optimizedGeometryId of a calculation can be obtained through the
GET "/calculations/{id}" end point.
An already present feature that goes along with this: for geometries that
were produced by an optimization calculation, the provenanceType is
"calculation", and the provenanceId is the ID of the optimization
calculation it came from. Thus, if a chain of optimizations were
performed to produce a geometry, one can back-track to the original
calculation/geometry that the chain …
> Save optimized geometry IDs in calculations

- flask/openbabel/src/openbabel_api.py
- flask/openbabel/src/server.py
- girder/molecules/molecules/molecule.py
- girder/molecules/molecules/utilities/async_requests.py
- girder/molecules/molecules/utilities/molecules.py
This adds options to choose the forcefield (default: 'mmff94') and
the number of optimization steps (default: 100) when generating 3D
coordinates for a molecule.
In the POST /molecules REST API, the forcefield can be specified with
"gen3dForcefield", and the number of steps can be specified with
"gen3dSteps". In the POST /molecules/{id}/3d REST API, the forcefield
can be specified with the "forcefield" query, and the number of steps
can be specified with the "steps" query.
The previous number of optimization steps was 50. This commit bumps
the default number of optimization steps up to 100, so the molecules
will probably be slightly different than before.
> Add forcefield and steps options for gen3d

- girder/molecules/molecules/molecule.py
For the end point POST /molecules/{id}/3d, the steps is a query, and
is thus treated as a string. Convert it to an int before calling
schedule_3d_coords_gen() with it.
This was not causing a problem with the web API since it the web API
automatically converts it to an int. However, it is a problem for
calling this end point in other contexts, including openchemistrypy. This
PR fixes the issue.
> Convert steps to int for generating 3D coordinates

- girder/molecules/molecules/calculation.py
- girder/molecules/molecules/molecule.py
- girder/molecules/molecules/utilities/molecules.py
If a 'name' or 'wikipedia' field are passed in via the body of a molecule those fields will be set. 
If 'name' or 'wikipedia' are included in the input parameters of a calculation and the molecule does not yet exist those fields will be set upon molecule creation. If the molecule already exists the fields are ignored.
> Allow user to pass in name or wikipedia link

- girder/molecules/molecules/molecule.py
If a user requests for 3D output of a molecule that does not have 3D
coordinates, return 'None' rather than raising an exception, as was
previously done.
This is done to address [this comment](https://github.com/OpenChemistry/openchemistrypy/pull/96/files/a83a1334301d930dac0c1fcfef31072c8ccb2bcc#r362954723) in openchemistry/openchemistrypy#96.
> Return None when 3D output requested for 0D mol

- girder/molecules/molecules/models/calculation.py
- girder/molecules/molecules/models/molecule.py
- girder/molecules/molecules/molecule.py
The Girder base class already uses the "find" name that would have been
used more naturally, so at least make the name conform to our coding
standards using snake_case and make it a little more explicitly
molecule.
> Make findmol -> find_molecule - fix inconsistency

- girder/notebooks/notebooks/notebooks/MultipleCalcs.ipynb
This example illustrates the ability to select the force field
and the number of steps when generating 3D coordinates.
Note also that the arguments `gen3d_forcefield` and `gen3d_steps`
may be passed to `oc.import_structure()` for 3D coordinate generation
when importing line formats like SMILES.
This is an example of using the features found in OpenChemistry/openchemistrypy#96
> Add example of setting gen3d options

- girder/molecules/molecules/models/calculation.py
The geometry ID is not being stored as an ObjectId currently. Thus,
if we try to query it as an ObjectId, we find no results. Fix this
by removing the ObjectId conversion.
Another alternative to fix this is to convert the geometry ID into
an ObjectId when it gets saved on the calculation. Let me know 
if that is preferred.
> Fix GET /calculations with a geometry ID

- girder/notebooks/notebooks/notebooks/ChainOptimizations.ipynb
This adds a notebook example of performing chain optimizations.
In this case, Open Babel generates the 3D coordinates, and then
ANI optimizes them, and then Psi4 optimizes them.
Open Babel -> ANI -> Psi4
The notebook then provides an example of calculating RMSD of the
two different geometries generated by ANI and Psi4.
Depends on: OpenChemistry/openchemistrypy#100
> Add example of chain optimizations with RMSD

- girder/molecules/molecules/calculation.py
- girder/molecules/molecules/models/calculation.py
- girder/molecules/molecules/models/geometry.py
- girder/molecules/molecules/models/molecule.py
- girder/molecules/molecules/molecule.py
This makes molecules, calculations, and geometries default to
being public, rather than private.
Fixes: #155
> Have models default to being public

- girder/queues/queues/__init__.py
- girder/queues/queues/models/queue.py
Following discussion at https://github.com/girder/girder/pull/3199
we no longer dynamically bind multiple handlers to the
'cumulus.taskflow.status_update' event.
Also, implement a cleanup function which is run at load time, to prevent
failed taskflows from taking up running slots in the queue forever.
Fixes: #179
> Improve robustness of the queue plugin

- docker/girder/Dockerfile
Girder [does not support the "latest-py3" tag anymore](https://discourse.girder.org/t/dropping-python-2-support/317/4).
The "latest" tag points to the python3 version, and python2 is no
longer supported by girder.
We can alternatively use a specific version, such as "3.1.0", if we want
to lock down a version.
> Use "latest" instead of "latest-py3" for girder

- girder/molecules/molecules/models/molecule.py
This regex was only matching strings that started with the name. Remove
the anchor so that any string that contains the name will match.
This makes our search match via "contains" rather than "starts with".
Fixes: #185
I tested this, and it seems to have fixed the issue.
> Remove string start anchor from name search

- girder/app/app/__init__.py
- girder/app/app/launch_taskflow.py
Rather than having ~7 restful API calls to launch a single taskflow,
add a single restful API endpoint that takes care of most of the logic.
This single API call optionally takes a clusterId. It will use that
cluster if provided. If not provided one, it will use the first cluster
it can find.
The body of the endpoint should contain two keys:
1. taskFlowBody
2. taskBody
That contain the bodies of the taskflow, and the task, respectively.
Depends on: Kitware/cumulus#362
Fixes: #187
> Add a single endpoint to launch taskflows

- girder/molecules/molecules/models/calculation.py
Starting in MongoDB 4.4, it is illegal to project an embedded document with any of the embedded document’s fields.
> Remove path collision
