girder/molecules/server/avogadro.py, girder/molecules/server/molecule.py
This extracts the molecular mass, formular, and atom counts for the
molecule, and stores them in the database. It requires some new API
added in AvogadroLibs master.
=> Added some logic to extract metadata for molecule

girder/molecules/server/models/calculation.py, girder/molecules/server/molecule.py
This makes it easier to see the full file/rescan it in future.
=> Save the fileId associated with calculations

scripts/bulk_import.py
This uses the file upload mechanism, and then calls molecule create to
add the data file.
=> Added a client to bulk upload data files

girder/molecules/server/avogadro.py, girder/molecules/server/calculation.py, girder/molecules/server/models/calculation.py, girder/molecules/server/molecule.py
Store these with the calculation so that they can be used to identify
the calculation.
=> Extract some of the calculation properties

scripts/bulk_import.py
Check that the me query succeeds, if not the token is likely invalid.
=> Minor error checking - is token valid?

girder/molecules/server/calculation.py, girder/molecules/server/models/cubecache.py
We need to add expiration of old cubes, the cubecache collection can be
discarded to regenerate the cubes if necessary.
=> Added a cube cache, massive speed ups on repeats

girder/molecules/server/calculation.py
=> Fix homo-lumo orbital index

girder/molecules/plugin_tests/molecules_test.py, girder/molecules/server/models/molecule.py, girder/molecules/server/molecule.py
=> Return _id rather than id

devops/docker/Dockerfile.circleci, girder/molecules/plugin_tests/conftest.py, girder/molecules/plugin_tests/data/water.inchi, girder/molecules/plugin_tests/molecules_test.py, girder/molecules/server/models/molecule.py, girder/molecules/server/molecule.py, girder/molecules/server/utilities/molecules.py
=> Ensure molecule has basic props on creation

girder/molecules/plugin_tests/data/aspirin.smi, girder/molecules/plugin_tests/molecules_test.py, girder/molecules/server/molecule.py, girder/molecules/server/openbabel.py, girder/molecules/server/utilities/molecules.py
Also added a smiles test that uses aspirin.
Also simplified some of the python code that uses
open babel to convert a 2D format into a 3D one.
=> Added ability to create a molecule with smiles

girder/molecules/server/openbabel.py
Add a start of InChI validator to prevent Open Babel crashes.
In my testing, this fixes most of the server crashes. I have
not yet found a way to make the server crash with an invalid
InChI while this validator is present. But we can add more to
the validator in the future if needed.
Fixes: #105
=> Add start of InChI validator to prevent OB crashes

girder/molecules/server/molecule.py, girder/molecules/server/openbabel.py, girder/molecules/server/utilities/molecules.py
This also includes a rest endpoint for getting SVG images
from molecules.
=> Save an SVG for molecules upon creation

girder/molecules/server/molecule.py
This also fixes the logs update to use $addToSet
instead of saving the molecule.
=> Allow users to patch molecule names

girder/molecules/server/molecule.py
This also recognizes that cjson is not required for 2d
outputs, but it is required for 3d outputs.
=> Allow 2d outputs to be obtained via GET

girder/molecules/server/models/molecule.py, girder/molecules/server/openbabel.py
=> Only auto-detect bonds if we have 3D coordinates

girder/molecules/molecules/calculation.py, girder/molecules/molecules/models/calculation.py, girder/molecules/molecules/utilities/pagination.py, girder/molecules/plugin_tests/calculations_test.py
Allow calculations to be searched with pagination and 
via entries such as `creatorId`.
=> Improve calculation search capabilities

girder/molecules/molecules/semantic/__init__.py, girder/molecules/molecules/semantic/jena.py, girder/molecules/molecules/semantic/virtuoso.py
This argument was removed in a recent [girder commit](https://github.com/girder/girder/commit/aacfdb1f7120516f09895dc55c0d93319a2260b1).
This commit fixes our tests.
=> Remove default argument for Setting.get

docker/Dockerfile
With Girder 3 will need to install the plugin.
=> Install OAuth plugin

girder/notebooks/notebooks/notebooks/MultipleCalcs.ipynb, girder/notebooks/notebooks/notebooks/SimultaneousCalcs.ipynb
This gives examples for:
1. Running simultaneous calculations in the same docker container.
2. Creating molecules that do not have 3D coordinates.
It also provides some extra examples such as what happens when
a 3D calculation is attempted on a 2D molecule.
=> Add notebook example for doing simultaneous calcs

girder/molecules/molecules/molecule.py, girder/molecules/molecules/utilities/molecules.py
This will be particularly useful when we import molecules from
other databases.
=> Added ability to specify provenance for molecules

girder/molecules/molecules/molecule.py
=> Conversions

girder/molecules/molecules/calculation.py
The code info looks something like this:
```
{
"name": "PSI4",
"version": "1.2.1"
}
```
=> Save the code info of calculations if provided

girder/molecules/molecules/calculation.py, girder/molecules/molecules/models/calculation.py
Also fixes a minor typo in find_id.
Signed-off-by: Brianna Major <brianna.major@kitware.com>
=> Expose the code information for calculations

girder/notebooks/notebooks/notebooks/ChainOptimizations.ipynb
This is the latest that also appears to be working.
=> Update notebook example to use torchani:1.2

.circleci/config.yml
See: https://github.com/girder/girder/issues/3298
=> Update various packages to avoid ContextualVersionConflict
